version: '2.1'
install-aws-cli:
        description: Easily install and configure the AWS CLI automatically in your jobs or commands.
        usage:
            version: "2.1"
            orbs:
                aws-cli: circleci/aws-cli@3.1
            jobs:
                aws-cli-example:
                    executor: aws-cli/default
                    steps:
                        - checkout
                        - aws-cli/setup:
                            profile-name: example
                        - run: echo "Run your code here"
            workflows:
                aws-cli:
                    jobs:
                        - aws-cli-example:
                            context: aws
orbs:
  aws-s3: circleci/aws-s3@3.1
jobs:
  build:
    docker:
      - image: 'cimg/python:3.10'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_1.txt
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          role-arn: 'arn:aws:iam::123456789012/role/VALID-S3-ROLE'
          to: 's3://circlecidemo/prefix'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/build_asset.txt
          install-aws-cli: true
          to: 's3://my-s3-bucket-name'
workflows:
  s3-example:
    jobs:
      - build

